name: Blog Generator

on:
  schedule:
    # Run at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        WP_USERNAME: ${{ secrets.WP_USERNAME }}
        WP_APP_PASS: ${{ secrets.WP_APP_PASS }}
        WP_URL: ${{ secrets.WP_URL }}
      run: |
        echo "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY" >> .env
        echo "WP_USERNAME=$WP_USERNAME" >> .env
        echo "WP_APP_PASS=$WP_APP_PASS" >> .env
        echo "WP_URL=$WP_URL" >> .env

    - name: Run blog generator
      run: python main.py

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          *.log
          .env 